Feature/event listeners
kcbryan10/View-Dine-Randomizer pull request #22
Opened 2021-11-02 03:00 UTC by Justin-Eicher

2021-11-02 03:10 UTC, Justin-Eicher commented
not functional, page still loads movies and recipes on page load.

2021-11-02 18:07 UTC, HighDynamics requested changes
- Remove function call from listener, use reference instead
- Functions packaged together in handler (inline or otherwise) so both can run on click

2021-11-03 00:40 UTC, HighDynamics approved these changes

2021-11-03 00:43 UTC, kcbryan10 approved these changes
looks good!

2021-11-03 00:43 UTC, merged